In [1]:
    filename = ["ind.cora.{}".format(name) for name in
                ['x', 'tx', 'allx', 'y', 'ty', 'ally', 'graph', 'test.index']]
    filename

['ind.cora.x',
 'ind.cora.tx',
 'ind.cora.allx',
 'ind.cora.y',
 'ind.cora.ty',
 'ind.cora.ally',
 'ind.cora.graph',
 'ind.cora.test.index']

Cora数据，包括数据下载，处理，加载等功能
        当数据的缓存文件存在时，将使用缓存文件，否则将下载、进行处理，并缓存到磁盘

        处理之后的数据可以通过属性 .data 获得，它将返回一个数据对象，包括如下几部分：
            * x: 节点的特征，维度为 2708 * 1433，类型为 np.ndarray
            * y: 节点的标签，总共包括7个类别，类型为 np.ndarray
            * adjacency_dict: 邻接信息，，类型为 dict
            * train_mask: 训练集掩码向量，维度为 2708，当节点属于训练集时，相应位置为True，否则False
            * val_mask: 验证集掩码向量，维度为 2708，当节点属于验证集时，相应位置为True，否则False
            * test_mask: 测试集掩码向量，维度为 2708，当节点属于测试集时，相应位置为True，否则False

In [2]:
import pickle

# 第一步为读取数据

## ind.cora.graph 为byte文件，打开后为字典形式，定义了图

## ind.cora.test.index 也是文本文件，需要用np.genfromtxt 打开

## 其余都是byte文件，打开后是稀疏矩阵表示的，我们需要把他们转成array形式

In [3]:
out = pickle.load(open('../GraphSage/data/cora/ind.cora.graph',"rb"),encoding="latin1")
out

defaultdict(list,
            {0: [633, 1862, 2582],
             1: [2, 652, 654],
             2: [1986, 332, 1666, 1, 1454],
             3: [2544],
             4: [2176, 1016, 2176, 1761, 1256, 2175],
             5: [1629, 2546, 1659, 1659],
             6: [1416, 1602, 1042, 373],
             7: [208],
             8: [281, 1996, 269],
             9: [2614, 723, 723],
             10: [476, 2545],
             11: [1655, 1839],
             12: [2661, 1001, 1318, 2662],
             13: [1810, 1701],
             14: [2034, 2075, 158, 2077, 2668],
             15: [2367, 1093, 1090, 1271, 1093],
             16: [2444, 1632, 970, 2642],
             17: [24, 2140, 1316, 1315, 927],
             18: [2082, 139, 1786, 1560, 2145],
             19: [1939],
             20: [1072, 2374, 2375, 2269, 2270],
             21: [1043, 2310],
             22: [1703, 1702, 2238, 39, 1234],
             23: [2159],
             24: [1701, 2139, 1636, 17, 2141, 598, 201],
             25: [

In [4]:
out = out.toarray() if hasattr(out,"toarray") else out
type(out)

collections.defaultdict

In [5]:
import numpy as np

In [7]:
test_index = np.genfromtxt('data/cora/ind.cora.test.index',dtype='int64')
test_index

array([2692, 2532, 2050, 1715, 2362, 2609, 2622, 1975, 2081, 1767, 2263,
       1725, 2588, 2259, 2357, 1998, 2574, 2179, 2291, 2382, 1812, 1751,
       2422, 1937, 2631, 2510, 2378, 2589, 2345, 1943, 1850, 2298, 1825,
       2035, 2507, 2313, 1906, 1797, 2023, 2159, 2495, 1886, 2122, 2369,
       2461, 1925, 2565, 1858, 2234, 2000, 1846, 2318, 1723, 2559, 2258,
       1763, 1991, 1922, 2003, 2662, 2250, 2064, 2529, 1888, 2499, 2454,
       2320, 2287, 2203, 2018, 2002, 2632, 2554, 2314, 2537, 1760, 2088,
       2086, 2218, 2605, 1953, 2403, 1920, 2015, 2335, 2535, 1837, 2009,
       1905, 2636, 1942, 2193, 2576, 2373, 1873, 2463, 2509, 1954, 2656,
       2455, 2494, 2295, 2114, 2561, 2176, 2275, 2635, 2442, 2704, 2127,
       2085, 2214, 2487, 1739, 2543, 1783, 2485, 2262, 2472, 2326, 1738,
       2170, 2100, 2384, 2152, 2647, 2693, 2376, 1775, 1726, 2476, 2195,
       1773, 1793, 2194, 2581, 1854, 2524, 1945, 1781, 1987, 2599, 1744,
       2225, 2300, 1928, 2042, 2202, 1958, 1816, 19

In [8]:
sorted_test_index = sorted(test_index)
sorted_test_index

[1708,
 1709,
 1710,
 1711,
 1712,
 1713,
 1714,
 1715,
 1716,
 1717,
 1718,
 1719,
 1720,
 1721,
 1722,
 1723,
 1724,
 1725,
 1726,
 1727,
 1728,
 1729,
 1730,
 1731,
 1732,
 1733,
 1734,
 1735,
 1736,
 1737,
 1738,
 1739,
 1740,
 1741,
 1742,
 1743,
 1744,
 1745,
 1746,
 1747,
 1748,
 1749,
 1750,
 1751,
 1752,
 1753,
 1754,
 1755,
 1756,
 1757,
 1758,
 1759,
 1760,
 1761,
 1762,
 1763,
 1764,
 1765,
 1766,
 1767,
 1768,
 1769,
 1770,
 1771,
 1772,
 1773,
 1774,
 1775,
 1776,
 1777,
 1778,
 1779,
 1780,
 1781,
 1782,
 1783,
 1784,
 1785,
 1786,
 1787,
 1788,
 1789,
 1790,
 1791,
 1792,
 1793,
 1794,
 1795,
 1796,
 1797,
 1798,
 1799,
 1800,
 1801,
 1802,
 1803,
 1804,
 1805,
 1806,
 1807,
 1808,
 1809,
 1810,
 1811,
 1812,
 1813,
 1814,
 1815,
 1816,
 1817,
 1818,
 1819,
 1820,
 1821,
 1822,
 1823,
 1824,
 1825,
 1826,
 1827,
 1828,
 1829,
 1830,
 1831,
 1832,
 1833,
 1834,
 1835,
 1836,
 1837,
 1838,
 1839,
 1840,
 1841,
 1842,
 1843,
 1844,
 1845,
 1846,
 1847,
 1848,
 1849,
 1850,

In [12]:
test_index

array([2692, 2532, 2050, 1715, 2362, 2609, 2622, 1975, 2081, 1767, 2263,
       1725, 2588, 2259, 2357, 1998, 2574, 2179, 2291, 2382, 1812, 1751,
       2422, 1937, 2631, 2510, 2378, 2589, 2345, 1943, 1850, 2298, 1825,
       2035, 2507, 2313, 1906, 1797, 2023, 2159, 2495, 1886, 2122, 2369,
       2461, 1925, 2565, 1858, 2234, 2000, 1846, 2318, 1723, 2559, 2258,
       1763, 1991, 1922, 2003, 2662, 2250, 2064, 2529, 1888, 2499, 2454,
       2320, 2287, 2203, 2018, 2002, 2632, 2554, 2314, 2537, 1760, 2088,
       2086, 2218, 2605, 1953, 2403, 1920, 2015, 2335, 2535, 1837, 2009,
       1905, 2636, 1942, 2193, 2576, 2373, 1873, 2463, 2509, 1954, 2656,
       2455, 2494, 2295, 2114, 2561, 2176, 2275, 2635, 2442, 2704, 2127,
       2085, 2214, 2487, 1739, 2543, 1783, 2485, 2262, 2472, 2326, 1738,
       2170, 2100, 2384, 2152, 2647, 2693, 2376, 1775, 1726, 2476, 2195,
       1773, 1793, 2194, 2581, 1854, 2524, 1945, 1781, 1987, 2599, 1744,
       2225, 2300, 1928, 2042, 2202, 1958, 1816, 19

In [13]:
y = pickle.load(open('data/cora/ind.cora.y','rb'),encoding='latin1')

In [14]:
np.arange(y.shape[0], y.shape[0] + 500)

array([140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
       153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
       166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
       179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
       192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
       205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217,
       218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230,
       231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243,
       244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256,
       257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269,
       270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282,
       283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295,
       296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308,
       309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 32

In [15]:
x = pickle.load(open('data/cora/ind.cora.x','rb'),encoding='latin1').toarray()

In [16]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [17]:
x.shape

(140, 1433)

In [18]:
allx.shape

NameError: name 'allx' is not defined

In [19]:
tx = pickle.load(open('data/cora/ind.cora.tx', 'rb'),encoding='latin1').toarray()

In [20]:
tx

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [21]:
tx.shape

(1000, 1433)

In [22]:
x = np.concatenate((allx, tx), axis=0)

NameError: name 'allx' is not defined

In [24]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [25]:
x.shape

(140, 1433)

In [26]:
pickle.load(open('data/cora/ind.cora.test.index','r'))

TypeError: a bytes-like object is required, not 'str'

In [27]:
y = pickle.load(open('data/cora/ind.cora.ty', 'rb'),encoding='latin1')

In [28]:
ally = pickle.load(open('data/cora/ind.cora.ally', 'rb'),encoding='latin1')

In [29]:
np.concatenate((ally,y),axis=0).argmax(axis=1)

array([3, 4, 4, ..., 1, 2, 6])

In [30]:
np.zeros(2700, dtype=np.bool)

<ipython-input-30-c224e57e884e>:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros(2700, dtype=np.bool)


array([False, False, False, ..., False, False, False])

In [31]:
len(out)

2708

In [32]:
graph = pickle.load(open("data/cora/ind.cora.graph", 'rb'), encoding='latin1')

In [33]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [34]:
edge_index = []
num_nodes = len(out)
for src, dst in graph.items():
    edge_index.extend([src, v] for v in dst)
    edge_index.extend([v, src] for v in dst)

In [35]:
sorted(edge_index)

[[0, 633],
 [0, 633],
 [0, 1862],
 [0, 1862],
 [0, 2582],
 [0, 2582],
 [1, 2],
 [1, 2],
 [1, 652],
 [1, 652],
 [1, 654],
 [1, 654],
 [2, 1],
 [2, 1],
 [2, 332],
 [2, 332],
 [2, 1454],
 [2, 1454],
 [2, 1666],
 [2, 1666],
 [2, 1986],
 [2, 1986],
 [3, 2544],
 [3, 2544],
 [4, 1016],
 [4, 1016],
 [4, 1256],
 [4, 1256],
 [4, 1761],
 [4, 1761],
 [4, 2175],
 [4, 2175],
 [4, 2176],
 [4, 2176],
 [4, 2176],
 [4, 2176],
 [5, 1629],
 [5, 1629],
 [5, 1659],
 [5, 1659],
 [5, 1659],
 [5, 1659],
 [5, 2546],
 [5, 2546],
 [6, 373],
 [6, 373],
 [6, 1042],
 [6, 1042],
 [6, 1416],
 [6, 1416],
 [6, 1602],
 [6, 1602],
 [7, 208],
 [7, 208],
 [8, 269],
 [8, 269],
 [8, 281],
 [8, 281],
 [8, 1996],
 [8, 1996],
 [9, 723],
 [9, 723],
 [9, 723],
 [9, 723],
 [9, 2614],
 [9, 2614],
 [10, 476],
 [10, 476],
 [10, 2545],
 [10, 2545],
 [11, 1655],
 [11, 1655],
 [11, 1839],
 [11, 1839],
 [12, 1001],
 [12, 1001],
 [12, 1318],
 [12, 1318],
 [12, 2661],
 [12, 2661],
 [12, 2662],
 [12, 2662],
 [13, 1701],
 [13, 1701],
 [13, 18

In [36]:
import itertools

In [37]:
itertools.groupby(edge_index)

In [38]:
for k, v in itertools.groupby(sorted(edge_index)):
    print(k,list(v))

[0, 633] [[0, 633], [0, 633]]
[0, 1862] [[0, 1862], [0, 1862]]
[0, 2582] [[0, 2582], [0, 2582]]
[1, 2] [[1, 2], [1, 2]]
[1, 652] [[1, 652], [1, 652]]
[1, 654] [[1, 654], [1, 654]]
[2, 1] [[2, 1], [2, 1]]
[2, 332] [[2, 332], [2, 332]]
[2, 1454] [[2, 1454], [2, 1454]]
[2, 1666] [[2, 1666], [2, 1666]]
[2, 1986] [[2, 1986], [2, 1986]]
[3, 2544] [[3, 2544], [3, 2544]]
[4, 1016] [[4, 1016], [4, 1016]]
[4, 1256] [[4, 1256], [4, 1256]]
[4, 1761] [[4, 1761], [4, 1761]]
[4, 2175] [[4, 2175], [4, 2175]]
[4, 2176] [[4, 2176], [4, 2176], [4, 2176], [4, 2176]]
[5, 1629] [[5, 1629], [5, 1629]]
[5, 1659] [[5, 1659], [5, 1659], [5, 1659], [5, 1659]]
[5, 2546] [[5, 2546], [5, 2546]]
[6, 373] [[6, 373], [6, 373]]
[6, 1042] [[6, 1042], [6, 1042]]
[6, 1416] [[6, 1416], [6, 1416]]
[6, 1602] [[6, 1602], [6, 1602]]
[7, 208] [[7, 208], [7, 208]]
[8, 269] [[8, 269], [8, 269]]
[8, 281] [[8, 281], [8, 281]]
[8, 1996] [[8, 1996], [8, 1996]]
[9, 723] [[9, 723], [9, 723], [9, 723], [9, 723]]
[9, 2614] [[9, 2614], [9

[306, 1551] [[306, 1551], [306, 1551]]
[306, 1572] [[306, 1572], [306, 1572]]
[306, 1584] [[306, 1584], [306, 1584]]
[306, 1640] [[306, 1640], [306, 1640]]
[306, 1651] [[306, 1651], [306, 1651]]
[306, 1656] [[306, 1656], [306, 1656]]
[306, 1705] [[306, 1705], [306, 1705]]
[306, 1770] [[306, 1770], [306, 1770]]
[306, 1771] [[306, 1771], [306, 1771]]
[306, 1772] [[306, 1772], [306, 1772]]
[306, 1775] [[306, 1775], [306, 1775]]
[306, 1779] [[306, 1779], [306, 1779]]
[306, 1781] [[306, 1781], [306, 1781]]
[306, 1782] [[306, 1782], [306, 1782]]
[306, 1787] [[306, 1787], [306, 1787]]
[306, 1797] [[306, 1797], [306, 1797]]
[306, 1798] [[306, 1798], [306, 1798]]
[306, 1799] [[306, 1799], [306, 1799]]
[306, 1802] [[306, 1802], [306, 1802]]
[306, 1804] [[306, 1804], [306, 1804]]
[306, 1805] [[306, 1805], [306, 1805]]
[306, 1856] [[306, 1856], [306, 1856]]
[306, 2045] [[306, 2045], [306, 2045]]
[306, 2046] [[306, 2046], [306, 2046]]
[306, 2048] [[306, 2048], [306, 2048]]
[306, 2078] [[306, 2078],

[636, 2233] [[636, 2233], [636, 2233]]
[637, 598] [[637, 598], [637, 598]]
[637, 1641] [[637, 1641], [637, 1641]]
[638, 271] [[638, 271], [638, 271]]
[638, 783] [[638, 783], [638, 783]]
[638, 808] [[638, 808], [638, 808]]
[638, 893] [[638, 893], [638, 893]]
[638, 924] [[638, 924], [638, 924]]
[638, 1773] [[638, 1773], [638, 1773]]
[638, 2387] [[638, 2387], [638, 2387]]
[639, 900] [[639, 900], [639, 900]]
[640, 395] [[640, 395], [640, 395]]
[640, 765] [[640, 765], [640, 765]]
[640, 894] [[640, 894], [640, 894]]
[640, 1090] [[640, 1090], [640, 1090]]
[640, 1598] [[640, 1598], [640, 1598]]
[640, 2420] [[640, 2420], [640, 2420]]
[641, 2704] [[641, 2704], [641, 2704]]
[642, 591] [[642, 591], [642, 591]]
[642, 2472] [[642, 2472], [642, 2472]]
[643, 573] [[643, 573], [643, 573]]
[643, 1167] [[643, 1167], [643, 1167]]
[643, 1538] [[643, 1538], [643, 1538]]
[643, 2407] [[643, 2407], [643, 2407]]
[644, 41] [[644, 41], [644, 41]]
[644, 596] [[644, 596], [644, 596]]
[644, 711] [[644, 711], [644, 7

[1013, 1625] [[1013, 1625], [1013, 1625]]
[1013, 1644] [[1013, 1644], [1013, 1644]]
[1013, 1661] [[1013, 1661], [1013, 1661]]
[1013, 1675] [[1013, 1675], [1013, 1675]]
[1013, 1729] [[1013, 1729], [1013, 1729]]
[1013, 1840] [[1013, 1840], [1013, 1840]]
[1013, 1841] [[1013, 1841], [1013, 1841]]
[1013, 1842] [[1013, 1842], [1013, 1842]]
[1013, 1843] [[1013, 1843], [1013, 1843]]
[1013, 1844] [[1013, 1844], [1013, 1844]]
[1013, 1845] [[1013, 1845], [1013, 1845]]
[1013, 1846] [[1013, 1846], [1013, 1846]]
[1013, 1847] [[1013, 1847], [1013, 1847]]
[1013, 1848] [[1013, 1848], [1013, 1848]]
[1013, 1849] [[1013, 1849], [1013, 1849]]
[1013, 1850] [[1013, 1850], [1013, 1850]]
[1013, 1851] [[1013, 1851], [1013, 1851]]
[1013, 2045] [[1013, 2045], [1013, 2045]]
[1014, 1558] [[1014, 1558], [1014, 1558]]
[1015, 698] [[1015, 698], [1015, 698]]
[1015, 1068] [[1015, 1068], [1015, 1068]]
[1015, 1143] [[1015, 1143], [1015, 1143]]
[1015, 1385] [[1015, 1385], [1015, 1385]]
[1015, 1425] [[1015, 1425], [1015, 14

[1359, 181] [[1359, 181], [1359, 181]]
[1359, 1464] [[1359, 1464], [1359, 1464]]
[1359, 1914] [[1359, 1914], [1359, 1914]]
[1359, 2278] [[1359, 2278], [1359, 2278]]
[1359, 2480] [[1359, 2480], [1359, 2480]]
[1360, 541] [[1360, 541], [1360, 541]]
[1360, 647] [[1360, 647], [1360, 647]]
[1360, 904] [[1360, 904], [1360, 904]]
[1360, 1650] [[1360, 1650], [1360, 1650]]
[1360, 1902] [[1360, 1902], [1360, 1902]]
[1360, 1904] [[1360, 1904], [1360, 1904]]
[1360, 1960] [[1360, 1960], [1360, 1960]]
[1360, 2491] [[1360, 2491], [1360, 2491]]
[1361, 565] [[1361, 565], [1361, 565]]
[1361, 1528] [[1361, 1528], [1361, 1528]]
[1362, 1351] [[1362, 1351], [1362, 1351]]
[1362, 1372] [[1362, 1372], [1362, 1372]]
[1362, 1914] [[1362, 1914], [1362, 1914]]
[1363, 507] [[1363, 507], [1363, 507]]
[1363, 1413] [[1363, 1413], [1363, 1413]]
[1364, 40] [[1364, 40], [1364, 40]]
[1365, 1702] [[1365, 1702], [1365, 1702]]
[1365, 1703] [[1365, 1703], [1365, 1703]]
[1365, 2509] [[1365, 2509], [1365, 2509]]
[1365, 2519] [[1

[1692, 574] [[1692, 574], [1692, 574]]
[1692, 756] [[1692, 756], [1692, 756], [1692, 756], [1692, 756]]
[1692, 1423] [[1692, 1423], [1692, 1423]]
[1692, 1469] [[1692, 1469], [1692, 1469]]
[1692, 1472] [[1692, 1472], [1692, 1472]]
[1692, 1514] [[1692, 1514], [1692, 1514]]
[1692, 2186] [[1692, 2186], [1692, 2186]]
[1692, 2187] [[1692, 2187], [1692, 2187]]
[1692, 2302] [[1692, 2302], [1692, 2302]]
[1692, 2345] [[1692, 2345], [1692, 2345]]
[1692, 2346] [[1692, 2346], [1692, 2346]]
[1692, 2347] [[1692, 2347], [1692, 2347]]
[1692, 2348] [[1692, 2348], [1692, 2348]]
[1692, 2349] [[1692, 2349], [1692, 2349]]
[1693, 434] [[1693, 434], [1693, 434]]
[1693, 965] [[1693, 965], [1693, 965]]
[1693, 1391] [[1693, 1391], [1693, 1391]]
[1693, 1524] [[1693, 1524], [1693, 1524]]
[1693, 2408] [[1693, 2408], [1693, 2408]]
[1694, 333] [[1694, 333], [1694, 333]]
[1695, 276] [[1695, 276], [1695, 276]]
[1695, 1463] [[1695, 1463], [1695, 1463]]
[1695, 2133] [[1695, 2133], [1695, 2133], [1695, 2133], [1695, 2133]

[1955, 2235] [[1955, 2235], [1955, 2235]]
[1956, 807] [[1956, 807], [1956, 807]]
[1956, 1226] [[1956, 1226], [1956, 1226]]
[1956, 1954] [[1956, 1954], [1956, 1954]]
[1956, 1955] [[1956, 1955], [1956, 1955]]
[1957, 979] [[1957, 979], [1957, 979]]
[1957, 1355] [[1957, 1355], [1957, 1355]]
[1957, 1441] [[1957, 1441], [1957, 1441]]
[1957, 1954] [[1957, 1954], [1957, 1954]]
[1957, 2241] [[1957, 2241], [1957, 2241]]
[1957, 2630] [[1957, 2630], [1957, 2630]]
[1958, 735] [[1958, 735], [1958, 735]]
[1958, 739] [[1958, 739], [1958, 739]]
[1958, 1237] [[1958, 1237], [1958, 1237]]
[1958, 1441] [[1958, 1441], [1958, 1441]]
[1958, 1881] [[1958, 1881], [1958, 1881]]
[1958, 1884] [[1958, 1884], [1958, 1884]]
[1958, 1954] [[1958, 1954], [1958, 1954]]
[1959, 119] [[1959, 119], [1959, 119]]
[1959, 132] [[1959, 132], [1959, 132]]
[1959, 379] [[1959, 379], [1959, 379], [1959, 379], [1959, 379]]
[1959, 904] [[1959, 904], [1959, 904]]
[1959, 2621] [[1959, 2621], [1959, 2621]]
[1960, 1360] [[1960, 1360], [196

[2248, 856] [[2248, 856], [2248, 856]]
[2248, 996] [[2248, 996], [2248, 996]]
[2248, 1071] [[2248, 1071], [2248, 1071]]
[2248, 1135] [[2248, 1135], [2248, 1135]]
[2248, 1138] [[2248, 1138], [2248, 1138]]
[2248, 1255] [[2248, 1255], [2248, 1255]]
[2248, 1257] [[2248, 1257], [2248, 1257], [2248, 1257], [2248, 1257]]
[2248, 1366] [[2248, 1366], [2248, 1366]]
[2248, 1461] [[2248, 1461], [2248, 1461]]
[2248, 1545] [[2248, 1545], [2248, 1545]]
[2248, 2249] [[2248, 2249], [2248, 2249]]
[2249, 368] [[2249, 368], [2249, 368]]
[2249, 1257] [[2249, 1257], [2249, 1257]]
[2249, 2130] [[2249, 2130], [2249, 2130]]
[2249, 2248] [[2249, 2248], [2249, 2248]]
[2249, 2518] [[2249, 2518], [2249, 2518]]
[2249, 2671] [[2249, 2671], [2249, 2671]]
[2250, 283] [[2250, 283], [2250, 283]]
[2250, 348] [[2250, 348], [2250, 348]]
[2250, 1138] [[2250, 1138], [2250, 1138]]
[2250, 1260] [[2250, 1260], [2250, 1260]]
[2251, 121] [[2251, 121], [2251, 121]]
[2251, 1158] [[2251, 1158], [2251, 1158]]
[2251, 2252] [[2251, 225

[2573, 2570] [[2573, 2570], [2573, 2570]]
[2574, 1186] [[2574, 1186], [2574, 1186]]
[2575, 1008] [[2575, 1008], [2575, 1008]]
[2576, 1680] [[2576, 1680], [2576, 1680]]
[2576, 2056] [[2576, 2056], [2576, 2056]]
[2576, 2311] [[2576, 2311], [2576, 2311]]
[2577, 1235] [[2577, 1235], [2577, 1235]]
[2577, 1663] [[2577, 1663], [2577, 1663]]
[2578, 27] [[2578, 27], [2578, 27]]
[2578, 2360] [[2578, 2360], [2578, 2360]]
[2579, 972] [[2579, 972], [2579, 972]]
[2579, 1086] [[2579, 1086], [2579, 1086], [2579, 1086], [2579, 1086]]
[2579, 1225] [[2579, 1225], [2579, 1225]]
[2580, 186] [[2580, 186], [2580, 186], [2580, 186], [2580, 186]]
[2580, 972] [[2580, 972], [2580, 972]]
[2580, 1228] [[2580, 1228], [2580, 1228]]
[2580, 1536] [[2580, 1536], [2580, 1536]]
[2581, 83] [[2581, 83], [2581, 83]]
[2581, 449] [[2581, 449], [2581, 449]]
[2582, 0] [[2582, 0], [2582, 0]]
[2582, 1166] [[2582, 1166], [2582, 1166]]
[2582, 1862] [[2582, 1862], [2582, 1862]]
[2583, 247] [[2583, 247], [2583, 247]]
[2584, 876] [[25

In [40]:
import torch

In [41]:
A = torch.ones(16, 10, 1433)

In [42]:
A

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        ...,

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1., 

In [44]:
Z = A.max(dim=1)

In [49]:
Z = Z.values

In [59]:
torch.nn.functional.normalize(Z, dim=1)

tensor([[0.0264, 0.0264, 0.0264,  ..., 0.0264, 0.0264, 0.0264],
        [0.0264, 0.0264, 0.0264,  ..., 0.0264, 0.0264, 0.0264],
        [0.0264, 0.0264, 0.0264,  ..., 0.0264, 0.0264, 0.0264],
        ...,
        [0.0264, 0.0264, 0.0264,  ..., 0.0264, 0.0264, 0.0264],
        [0.0264, 0.0264, 0.0264,  ..., 0.0264, 0.0264, 0.0264],
        [0.0264, 0.0264, 0.0264,  ..., 0.0264, 0.0264, 0.0264]])

In [29]:
X = np.random.random([10,2])

In [30]:
X

array([[0.03746864, 0.80927997],
       [0.79770484, 0.19432859],
       [0.80623289, 0.6861445 ],
       [0.91453167, 0.92568568],
       [0.36607649, 0.14559099],
       [0.11303267, 0.03636792],
       [0.89383864, 0.11374832],
       [0.36296346, 0.55586259],
       [0.2991982 , 0.66655096],
       [0.03193921, 0.10703085]])

In [31]:
index = [6,2,1,4]

In [33]:
sort_index = sorted(index)

In [34]:
X[index] = X[sort_index]

In [35]:
X

array([[0.03746864, 0.80927997],
       [0.36607649, 0.14559099],
       [0.80623289, 0.6861445 ],
       [0.91453167, 0.92568568],
       [0.89383864, 0.11374832],
       [0.11303267, 0.03636792],
       [0.79770484, 0.19432859],
       [0.36296346, 0.55586259],
       [0.2991982 , 0.66655096],
       [0.03193921, 0.10703085]])